# ------------------------------------------------------------
# Hugo site configuration for Wowchemy v5
# ------------------------------------------------------------

baseURL: "https://example.com/"
title: "My Academic Site"
languageCode: "en-us"

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5

ignoreLogs:
  - 'unrecognized render hook template'
  - 'found no layout file for "wowchemycms_config"'

enableGitInfo: true

pagination:
  pagerSize: 10

outputFormats:
  wowchemycms_config:
    mediaType: application/json
    baseName: config
    isPlainText: true
    notAlternative: true

outputs:
  home:
    - HTML
    - wowchemycms_config
